//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Doctor_appointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital_location
    {
        public Hospital_location()
        {
            this.ListofDoctors = new HashSet<ListofDoctor>();
        }
    
        public int id { get; set; }
        public string Hospital_Location1 { get; set; }
    
        public virtual ICollection<ListofDoctor> ListofDoctors { get; set; }
    }
}
