//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Doctor_appointment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalApplicationEntities : DbContext
    {
        public HospitalApplicationEntities()
            : base("name=HospitalApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Hospital_location> Hospital_location { get; set; }
        public DbSet<ListofDoctor> ListofDoctors { get; set; }
        public DbSet<Specialty> Specialties { get; set; }
        public DbSet<register> registers { get; set; }
        public DbSet<Timeslot> Timeslots { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
    }
}
