//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Doctor_appointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListofDoctor
    {
        public ListofDoctor()
        {
            this.Timeslots = new HashSet<Timeslot>();
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int id { get; set; }
        public Nullable<int> locid { get; set; }
        public string Doctorname { get; set; }
        public Nullable<int> Specialityid { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual Hospital_location Hospital_location { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual ICollection<Timeslot> Timeslots { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
